---
- name: Ensure {{ neutron_heater_dest_path }} exits
  file:
    path: "{{ neutron_heater_dest_path }}"
    state: directory
    mode: 0755


- name: Clone neutron-heater repository
  ansible.builtin.git:
    repo: "{{ neutron_heater_repo }}"
    version: "{{ neutron_heater_version }}"
    dest: "{{ neutron_heater_dest_path }}"


- name: Ensure python3-virtualenv package is installed
  package:
    name: python3-virtualenv
    state: present


- name: Install neutron-heater in the virtualenv {{ neutron_heater_venv_path }}
  ansible.builtin.pip:
    name: "file://{{ neutron_heater_dest_path }}"
    virtualenv: "{{ neutron_heater_venv_path }}"
    virtualenv_site_packages: yes
  