---
- name: Ensure podman is installed
  become: true
  ansible.builtin.package:
    name: podman
    state: present

- name: "Ensure {{ ansible_env.HOME }}/.config/openstack directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/openstack"
    state: directory

- name: Copy clouds.yml file
  ansible.builtin.copy:
    src: "{{ clouds_yaml_path }}"
    dest: "{{ ansible_env.HOME }}/.config/openstack/clouds.yaml"

- name: Prepare os_vif config file
  ansible.builtin.copy:
    dest: "/tmp/neutron_heater.conf"
    content: |
      [os_vif_ovs]
      ovsdb_connection=unix:/var/run/openvswitch/db.sock
