---
- name: Run neutron-heater container to clean resources
  become: true
  containers.podman.podman_container:
    name: neutron-heater
    image: "{{ neutron_heater_image }}"
    network: host
    privileged: true
    detach: false
    recreate: true
    volumes:
      - "/var/run/openvswitch:/var/run/openvswitch"
      - "{{ ansible_env.HOME }}/.config/openstack/:/root/.config/openstack"
      - "/tmp/neutron_heater.conf:/neutron_heater.conf"
    command: "clean \
      --cloud-name {{ neutron_heater_cloud_name }} \
      --concurrency {{ neutron_heater_concurrency }} \
      --insecure \
      --config-file /neutron_heater.conf"
